dist: xenial   # required for Python >= 3.7

before_install:
  - sudo apt-get install -y ffmpeg inkscape texlive-extra-utils texlive-latex-extra pdf2svg
  
addons:
  apt:
    update: true

cache:
  - apt
  - pip
  
language: python
python:
  - "2.7"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
  
# command to run tests
script:
  - mkdir ./tests/html_out
  - mkdir ./tests/pdf_out
  - mkdir ./tests/pdf_out/tmp
  - cd ./tests/ && pytest
